default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: api_crud_ruby_test

production:
  <<: *default
  host: <%= ENV['DBP_HOSTNAME'] %>
  port: <%= ENV['DBP_PORT'] %>
  database: <%= ENV['DBP_DATABASE'] %>
  username: <%= ENV['DBP_USERNAME'] %>
  password: <%= ENV['DBP_PASSWORD'] %>